### ISSUE TITLE
Required in properties.schema that shouldn't be

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-articleBlockSlider#9] opened 2016-08-02 10:18 UTC
When using this with the new AT0.2.0 and FW2.0.11 there is a Required property of Minimum Height which is causing articles not to save if you are not using block slider in that article.

I'm not sure if you can just change Required-true to Required-false without causing issues when you do actually want to use it?

**Comment by OscarArango** [comment] 2016-10-25 15:35
I have confirmed this today as well.  2 months since this was posted, I'm sure someone has figured out a fix by now, can this thread be updated with a fix or solution.

**Comment by moloko** [comment] 2016-10-25 16:20
just updated properties.schema - try again now and let me know how you get on

**Comment by OscarArango** [comment] 2016-10-25 16:47
This shouldn't have been closed.  I tested the zip file from here and it did not work, there were still some changes left on properties.scheme file I've listed below:
1. _minHeight = "required":false,
2. change (`"validators": ["required", "number"],`) to (`"validators": ["number"],`)

Now it's resloved. without require it.

thanks,

**Comment by hbaileylxd** [comment] 2016-10-25 16:50
Ah sorry Oscar!

**Comment by OscarArango** [comment] 2016-10-25 16:52
I think you can close it unless you need to update code.  thanks

**Comment by moloko** [comment] 2016-10-25 16:56
@OscarArango oops sorry about that try again now

**Closed as completed** 2016-10-25 17:04 UTC

**Comment by OscarArango** [comment] 2016-10-25 18:12
No problem, let me know if you want this version to reference  so that the edits can be made to your master version

thanks,

OSCAR ARANGO, MCP SENIOR WEB DEVELOPER
B. BOYLE DESIGN, INC. | GRAPHIC | DIGITAL | PRINT | INTERACTIVE | MOBILE
BUZZ ME 401.383.8041 x4#  file://///tel/1-401-383-8041VISIT  WWW.BBOYLEDESIGN.COM http://www.bboyledesign.com/
